#!/usr/bin/env python3
"""Generate mani.yaml from repos.txt. Edit repos.txt, not this file."""

HEADER = """# Generated by tools/gen_manifest.py — do not hand-edit, edit repos.txt instead
sync_gitignore: false
sync_remotes: false

specs:
  fast:
    output: table
    parallel: true
    forks: 12
    ignore_errors: true
    ignore_non_existing: true

targets:
  legacy:
    tags: [legacy]
  new:
    tags: [new]

tasks:
  shas:
    desc: "Record the exact commit every finding came from"
    target: legacy
    spec: fast
    cmd: git rev-parse HEAD

  lock-readonly:
    desc: "Make pushes to legacy repos fail"
    target: legacy
    spec: fast
    cmd: git remote set-url --push origin DISABLED-READ-ONLY

  check-readonly:
    desc: "Confirm the push URL is disabled"
    target: legacy
    spec: fast
    cmd: git remote get-url --push origin

projects:
"""

def main():
    lines = [HEADER]
    count = {"core": 0, "likely": 0, "unknown": 0, "new": 0}

    with open("repos.txt") as f:
        for raw in f:
            raw = raw.strip()
            if not raw or raw.startswith("#"):
                continue
            parts = raw.split()
            if len(parts) < 3:
                print(f"skipping malformed line: {raw}")
                continue
            name, url, status = parts[0], parts[1], parts[2]
            count[status] = count.get(status, 0) + 1

            if status == "new":
                path = f"repos/new/{name}"
                lines.append(f"""  {name}:
    path: {path}
    url: {url}
    tags: [new]
""")
            else:
                path = f"repos/legacy/{name}"
                depth = "" if status == "core" else " --depth 1"
                lines.append(f"""  {name}:
    path: {path}
    url: {url}
    tags: [legacy, {status}]
    single_branch: true
    clone: git clone{depth} --single-branch {url} {path}
""")

    with open("mani.yaml", "w") as f:
        f.write("".join(lines))

    print("wrote mani.yaml")
    print("counts:", count)

if __name__ == "__main__":
    main()